Option to allow unauthorized connections
regadas/trino-js-client pull request #166
Opened 2023-01-20 13:53 UTC by elferherrera

Allow unauthorized connections

2023-01-21 07:54 UTC, regadas reviewed
Thanks for this @elferherrera :heart: 

there are some linting issues, can you take a look?

2023-01-21 07:55 UTC, regadas commented on src/index.ts
> +  readonly verify?: Boolean;
Here wdyt of renaming to smth like `verifySSLCert`; We should also default to true

2023-01-23 09:16 UTC, elferherrera commented on src/index.ts
> +  readonly verify?: Boolean;
Sure. I can change that

2023-01-23 09:17 UTC, elferherrera commented
> there are some linting issues, can you take a look?
Sorry. I'm a node novice. How do I apply linting?

2023-01-25 16:49 UTC, regadas requested changes
To test lint you can `yarn test:lint`. Also it would be great if we didn't include formatting changes.

Once again Thx!

2023-01-25 16:49 UTC, regadas commented on src/index.ts
> +      rejectUnauthorized: options.verifySSLCert
Hi @elferherrera here you will need to do smth like 
```suggestion
      rejectUnauthorized: options.verifySSLCert ?? DEFAULT_VERIFY_SSL_CERT
```

2023-01-26 07:28 UTC, regadas approved these changes
🙌 Thx @elferherrera!

2023-01-26 07:45 UTC, merged